-- M9 FINANCIAL ECOSYSTEM: DEFINITIVE BACKEND SCHEMA
-- Paste this into the Supabase SQL Editor and run it.

-- 1. Ensure the Profiles table exists for user metadata
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    avatar_url TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. DRESSES TABLE (Active Lines / Product Editor)
-- Ensure user_id exists and is linked to auth.users
CREATE TABLE IF NOT EXISTS public.dresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
    content JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- If the table existed without user_id, add it now (safe check)
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='dresses' AND column_name='user_id') THEN
        ALTER TABLE public.dresses ADD COLUMN user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid();
    END IF;
END $$;

-- 3. ENTRIES TABLE (Portfolio Hub / Strategic Notes)
-- Explicitly stores title, original_text, and the user_id owner
CREATE TABLE IF NOT EXISTS public.entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
    title TEXT NOT NULL,
    original_text TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.entries ENABLE ROW LEVEL SECURITY;

-- 5. RLS POLICIES (Privacy Protection)

-- Profiles
DROP POLICY IF EXISTS "Manage own profile" ON public.profiles;
CREATE POLICY "Manage own profile" ON public.profiles
    FOR ALL TO authenticated USING (auth.uid() = id);

-- Dresses (Active Lines)
DROP POLICY IF EXISTS "Manage own dresses" ON public.dresses;
CREATE POLICY "Manage own dresses" ON public.dresses
    FOR ALL TO authenticated USING (auth.uid() = user_id);

-- Entries (Portfolio Hub)
DROP POLICY IF EXISTS "Manage own entries" ON public.entries;
CREATE POLICY "Manage own entries" ON public.entries
    FOR ALL TO authenticated USING (auth.uid() = user_id);

-- 6. AUTOMATIC PROFILE CREATION TRIGGER
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'avatar_url'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger binding
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 7. PERFORMANCE INDEXES
CREATE INDEX IF NOT EXISTS idx_dresses_user_id ON public.dresses(user_id);
CREATE INDEX IF NOT EXISTS idx_entries_user_id ON public.entries(user_id);