-- M9 Financial Ecosystem: Database Schema Setup
-- Paste this script into the Supabase SQL Editor (SQL Tools -> New Query)

-- 1. Create the 'dresses' table to store production line data
CREATE TABLE IF NOT EXISTS public.dresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
    content JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS) to protect user data
ALTER TABLE public.dresses ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy to allow users to manage ONLY their own data
-- This covers SELECT, INSERT, UPDATE, and DELETE
CREATE POLICY "Users can manage their own dresses" 
ON public.dresses 
FOR ALL 
TO authenticated 
USING (auth.uid() = user_id) 
WITH CHECK (auth.uid() = user_id);

-- 4. Create an index on user_id for faster queries in multi-user environments
CREATE INDEX IF NOT EXISTS idx_dresses_user_id ON public.dresses(user_id);

-- Instructions:
-- After running this, ensure your Supabase project has Email Auth enabled (it is by default).
-- Users will now be able to save and load their clothing production plans securely.
