
-- ==========================================
-- M9 MONEY MAKER PLANNER: CORE DATABASE SCHEMA
-- ==========================================

-- 1. USER PROFILES
-- Stores extended metadata for the authenticated users.
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    avatar_url TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ACTIVE PRODUCTION LINES (Product Editor Data)
-- This table stores all calculated production models, costs, and sales projections.
-- Content is stored as JSONB to allow for flexible garment configuration.
CREATE TABLE IF NOT EXISTS public.dresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
    content JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. FINANCIAL HUB ENTRIES (Portfolio Ledger / Strategic Notes)
-- Stores strategic planning data, ledger titles, and financial reasoning.
CREATE TABLE IF NOT EXISTS public.entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
    title TEXT NOT NULL,
    original_text TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. SECURITY: ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.entries ENABLE ROW LEVEL SECURITY;

-- 5. ACCESS POLICIES: ISOLATION BY USER
-- Ensures users can only access their own production and financial data.

-- Profiles: Users can manage their own profile info
DROP POLICY IF EXISTS "Users can manage own profile" ON public.profiles;
CREATE POLICY "Users can manage own profile" ON public.profiles
    FOR ALL TO authenticated USING (auth.uid() = id);

-- Active Lines: Users can CRUD their own production lines
DROP POLICY IF EXISTS "Users can manage own active lines" ON public.dresses;
CREATE POLICY "Users can manage own active lines" ON public.dresses
    FOR ALL TO authenticated USING (auth.uid() = user_id);

-- Financial Hub: Users can CRUD their own ledger entries
DROP POLICY IF EXISTS "Users can manage own hub entries" ON public.entries;
CREATE POLICY "Users can manage own hub entries" ON public.entries
    FOR ALL TO authenticated USING (auth.uid() = user_id);

-- 6. AUTOMATION: UPDATED_AT TIMESTAMP TRIGGER
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_dresses_updated_at BEFORE UPDATE ON public.dresses FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER tr_entries_updated_at BEFORE UPDATE ON public.entries FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 7. AUTOMATION: PROFILE INITIALIZATION
-- Automatically creates a profile record when a new user signs up.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'avatar_url'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 8. OPTIMIZATION: PERFORMANCE INDEXES
CREATE INDEX IF NOT EXISTS idx_active_lines_user ON public.dresses(user_id);
CREATE INDEX IF NOT EXISTS idx_financial_hub_user ON public.entries(user_id);
CREATE INDEX IF NOT EXISTS idx_hub_title ON public.entries(title);
